import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pilot app [NextJS]",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="h-20 w-full border-b-2 flex items-center justify-between p-4">
          <div className="">
            Medium
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
